export const INSURANCE_PRODUCTS = [
  'Term Life',
  'Whole Life',
  'ULIP',
  'Endowment Plan',
  'Child Plan',
  'Retirement / Pension Plan',
  'Health Insurance',
  'Corporate / Group Health',
  'Personal Accident',
  'Critical Illness',
  'Motor Insurance',
  'Home Insurance',
  'Travel Insurance',
  'Marine Insurance',
  'Fire Insurance',
  'Corporate / Group Insurance',
  'Other',
];
